---
development:
  cloud_name: sharona
  api_key: '167699946475855'
  api_secret: XY0Lh7dcv4-SriKu8Rauh52Q1eE
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: sharona
  api_key: '167699946475855'
  api_secret: XY0Lh7dcv4-SriKu8Rauh52Q1eE
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: sharona
  api_key: '167699946475855'
  api_secret: XY0Lh7dcv4-SriKu8Rauh52Q1eE
  enhance_image_tag: true
  static_image_support: false
